# Generated by Django 5.2.5 on 2025-08-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=130)),
                ('Timestamp', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
