# Generated by Django 5.2.5 on 2025-08-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='phone',
            new_name='slug',
        ),
    ]
